name: Tiago Maluta
permalink: :year/:month/:day/:title
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : yourname@gmail.com
  github : maluta
  twitter : maluta

# Links in the navigation, you can modify both link name and link url
nav:
   Home: http://maluta.github.io/
   Diary: http://maluta.github.io/ml-diary

   
markdown: kramdown
highlighter: rouge
